### ISSUE TITLE
FirewallExtension

### ISSUE THREAD

**Issue by tguenneguez** [suchja/wix-toolset#3]
Hi,

I try to use [FirewallExtension](http://schemas.microsoft.com/wix/FirewallExtension) but I have the following error :
$ wine /home/xclient/wix/candle.exe -arch x64 XXX.wxs
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
Windows Installer XML Toolset Compiler version 3.9.1006.0
Copyright (c) Outercurve Foundation. All rights reserved.
observ.wxs
Z:\builds\directory\XX.wxs(93) : error CNDL0200 : The File element contains an unhandled extension element 'WixFirewallExtension:FirewallException'.  Please ensure that the extension for elements in the 'http://schemas.microsoft.com/wix/FirewallExtension' namespace has been provided.
Z:\builds\directory\XX.wxs(126) : error CNDL0200 : The File element contains an unhandled extension element 'WixFirewallExtension:FirewallException'.  Please ensure that the extension for elements in the 'http://schemas.microsoft.com/wix/FirewallExtension' namespace has been provided.

Thanks
Thomas

**Comment by suchja** [comment]
Hi Thomas,

sorry, but I haven't used this for several years now. So I have no idea what exactly the problem is.

Have you tested it with a simple project without any extensions? I see the the message 
> Application tried to create a window, but no driver could be loaded.
> Make sure that your X server is running and that $DISPLAY is set correctly.

I can't remember whether that occurs frequently and doesn't mean anything or whether it indicates, that maybe the xserver-Container is not running properly. I would recommend using a very simple project for wix to check that the containers are running properly. Then you should check what the problem with the *FirewallExtension* might be.

Another problem could be that the wix-Version in this image is way to old (in case you haven't updated it).

All the best
Jan

**Comment by tguenneguez** [comment]
Hi,

WixFirewallExtension need the DLL WixFirewallExtension.dll.
I forgot option :
-ext WixFirewallExtension.dll -ext WixUtilExtension.dll
I try again and give you more informations.

Thanks
Thomas
